global:
  message: Welcome to customer service prod environment!!

server: 
  port: 8083

message: Hello from prod!

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/customer_dev
    username: root
    password: root
  jpa: 
    hibernate:
      ddl-auto: update
    show-sql: false
