global:
  message: Welcome to customer service dev environment!!

server:
  port: 8082

message: Hello from Dev!

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/customer_master
    username: root
    password: test
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    database-platform: org.hibernate.dialect.MySQL8Dialect
