spring:
 application:
  name: customer-service
datasource:
  url: jdbc:mySql://localhost:3306/ecommerce
  driverClassName: com.mysql.cj.jdbc.Driver
spring:
 jpa: 
  hibernate:
   ddl-auto: update
      show-sql: false
