global:
 message: Welcome to customer service prod environment!!
server: 
 port: 8082
message: Hello from prod!
datasource:
  url: jdbc:mySql://localhost:3306/customer_dev
  username: root
  password: root
spring:
 jpa: 
  hibernate:
   ddl-auto: update
      show-sql: false
