global:
  message: Welcome to order service dev environment!!

server: 
  port: 8084

message: Hello from order Dev!

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/order_master
    username: root
    password: test
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa: 
    hibernate:
      ddl-auto: update
    show-sql: false
    database-platform: org.hibernate.dialect.MySQL8Dialect
