global:
 message: Welcome to order service dev environment!!
server: 
 port: 8082
message: Hello from order Dev!
datasource:
  url: jdbc:mySql://localhost:3306/order_dev
  username: root
  password: root
spring:
 jpa: 
  hibernate:
   ddl-auto: update
      show-sql: false
